### ISSUE TITLE
[Not an issue] using yr.no  source

### ISSUE THREAD

**Issue by Bitti09** [jimmerioles/progressive-weather-app#1]
did a quick and maybe verry dirty switch to yr.no as a source.
Disadvantage:
- A second api is required to get  Location Name & Country 
   (I've used the  json api 'nominatim' from openstreetmap.org  for this)
- No text description for the weather 
- Much more weather icons ids.(didn't added that part from yr.no api yet )

Changes that i did: https://github.com/Bitti09/progressive-weather-app/commit/5f05282a618c852d6f92053fc8ec00ad6dc84a65
-> https://bitti09.github.io/progressive-weather-app/

Btw : i get 100/100 on Lighthouse with your source :smiley:

**Comment by jimmerioles** [comment]
Thanks for the heads up man! That was really helpful I really appreciate it :+1: 

I am currently improving the app based on the feedback I received.

**Comment by Bitti09** [comment]
yr.no apis are really amazing  :smiley: 
pushed a new update to my fork: 
Added sunrise/set &moonrise/set from yr.no  + replaced the icons with weathericons.io ones (which currently seems to  force a score of 91/100  when using  it as the big weather one :(    )

**Comment by jimmerioles** [comment]
Looking great man! 

Btw, I've made the decision to wait for vue-cli's stable release before adding the new improvements.
